<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Membership;
use App\Models\MembershipCategory;

class CommitteeMemberSeeder extends Seeder
{
    public function run()
    {
        // Get categories
        $president = MembershipCategory::where('slug', 'president')->first();
        $seniorVicePresident = MembershipCategory::where('slug', 'senior-vice-president')->first();
        $vicePresidents = MembershipCategory::where('slug', 'vice-presidents')->first();
        $generalSecretary = MembershipCategory::where('slug', 'general-secretary')->first();
        $secretary = MembershipCategory::where('slug', 'secretary')->first();
        $treasurer = MembershipCategory::where('slug', 'treasurer')->first();
        $centralMembers = MembershipCategory::where('slug', 'central-members')->first();

        $members = [
            // Executive Committee
            [
                'full_name' => 'बिपुल पोखरेल',
                'email' => 'bipul.pokharel@fnjnepal.org',
                'phone' => '9841234567',
                'citizenship_number' => '12-01-75-12345',
                'date_of_birth' => '1975-05-15',
                'gender' => 'male',
                'address' => 'काठमाडौं, नेपाल',
                'education' => 'पत्रकारितामा स्नातकोत्तर',
                'experience_years' => 25,
                'current_workplace' => 'नेपाल पत्रकार महासंघ',
                'position' => 'अध्यक्ष',
                'membership_type' => 'life',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000001',
                'approved_at' => now()->subMonths(6),
                'category_id' => $president->id,
            ],
            [
                'full_name' => 'रमेश बिष्ट',
                'email' => 'ramesh.bista@fnjnepal.org',
                'phone' => '9841234568',
                'citizenship_number' => '12-01-76-12346',
                'date_of_birth' => '1976-08-20',
                'gender' => 'male',
                'address' => 'पोखरा, नेपाल',
                'education' => 'पत्रकारितामा स्नातक',
                'experience_years' => 22,
                'current_workplace' => 'राष्ट्रिय दैनिक',
                'position' => 'वरिष्ठ उपाध्यक्ष',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000002',
                'approved_at' => now()->subMonths(6),
                'category_id' => $seniorVicePresident->id,
            ],
            [
                'full_name' => 'सुनिता श्रेष्ठ',
                'email' => 'sunita.shrestha@fnjnepal.org',
                'phone' => '9841234569',
                'citizenship_number' => '12-01-78-12347',
                'date_of_birth' => '1978-03-10',
                'gender' => 'female',
                'address' => 'ललितपुर, नेपाल',
                'education' => 'जनसञ्चारमा स्नातकोत्तर',
                'experience_years' => 18,
                'current_workplace' => 'नेपाल टेलिभिजन',
                'position' => 'उपाध्यक्ष',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000003',
                'approved_at' => now()->subMonths(6),
                'category_id' => $vicePresidents->id,
            ],
            [
                'full_name' => 'राजेश आचार्य',
                'email' => 'rajesh.acharya@fnjnepal.org',
                'phone' => '9841234570',
                'citizenship_number' => '12-01-77-12348',
                'date_of_birth' => '1977-11-25',
                'gender' => 'male',
                'address' => 'भक्तपुर, नेपाल',
                'education' => 'पत्रकारितामा स्नातक',
                'experience_years' => 20,
                'current_workplace' => 'कान्तिपुर दैनिक',
                'position' => 'उपाध्यक्ष',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000004',
                'approved_at' => now()->subMonths(6),
                'category_id' => $vicePresidents->id,
            ],
            [
                'full_name' => 'अनिता गुरुङ',
                'email' => 'anita.gurung@fnjnepal.org',
                'phone' => '9841234571',
                'citizenship_number' => '12-01-79-12349',
                'date_of_birth' => '1979-07-12',
                'gender' => 'female',
                'address' => 'काठमाडौं, नेपाल',
                'education' => 'जनसञ्चारमा स्नातक',
                'experience_years' => 16,
                'current_workplace' => 'हिमालयन टाइम्स',
                'position' => 'महासचिव',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000005',
                'approved_at' => now()->subMonths(6),
                'category_id' => $generalSecretary->id,
            ],
            [
                'full_name' => 'प्रकाश थापा',
                'email' => 'prakash.thapa@fnjnepal.org',
                'phone' => '9841234572',
                'citizenship_number' => '12-01-80-12350',
                'date_of_birth' => '1980-02-28',
                'gender' => 'male',
                'address' => 'चितवन, नेपाल',
                'education' => 'पत्रकारितामा स्नातक',
                'experience_years' => 15,
                'current_workplace' => 'नागरिक दैनिक',
                'position' => 'सचिव',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000006',
                'approved_at' => now()->subMonths(6),
                'category_id' => $secretary->id,
            ],
            [
                'full_name' => 'सरिता पौडेल',
                'email' => 'sarita.poudel@fnjnepal.org',
                'phone' => '9841234573',
                'citizenship_number' => '12-01-81-12351',
                'date_of_birth' => '1981-09-18',
                'gender' => 'female',
                'address' => 'बुटवल, नेपाल',
                'education' => 'व्यवस्थापनमा स्नातक',
                'experience_years' => 14,
                'current_workplace' => 'गोरखापत्र दैनिक',
                'position' => 'कोषाध्यक्ष',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000007',
                'approved_at' => now()->subMonths(6),
                'category_id' => $treasurer->id,
            ],
            
            // Central Members
            [
                'full_name' => 'दिनेश कुमार',
                'email' => 'dinesh.kumar@fnjnepal.org',
                'phone' => '9841234574',
                'citizenship_number' => '12-01-82-12352',
                'date_of_birth' => '1982-04-05',
                'gender' => 'male',
                'address' => 'धनगढी, नेपाल',
                'education' => 'पत्रकारितामा स्नातक',
                'experience_years' => 12,
                'current_workplace' => 'सुदूरपश्चिम दैनिक',
                'position' => 'केन्द्रीय सदस्य',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000008',
                'approved_at' => now()->subMonths(6),
                'category_id' => $centralMembers->id,
            ],
            [
                'full_name' => 'मीरा राई',
                'email' => 'mira.rai@fnjnepal.org',
                'phone' => '9841234575',
                'citizenship_number' => '12-01-83-12353',
                'date_of_birth' => '1983-12-22',
                'gender' => 'female',
                'address' => 'इलाम, नेपाल',
                'education' => 'जनसञ्चारमा स्नातक',
                'experience_years' => 11,
                'current_workplace' => 'पूर्वाञ्चल दैनिक',
                'position' => 'केन्द्रीय सदस्य',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000009',
                'approved_at' => now()->subMonths(6),
                'category_id' => $centralMembers->id,
            ],
            [
                'full_name' => 'गोविन्द खड्का',
                'email' => 'govinda.khadka@fnjnepal.org',
                'phone' => '9841234576',
                'citizenship_number' => '12-01-84-12354',
                'date_of_birth' => '1984-06-14',
                'gender' => 'male',
                'address' => 'नेपालगञ्ज, नेपाल',
                'education' => 'पत्रकारितामा स्नातक',
                'experience_years' => 10,
                'current_workplace' => 'मध्यपश्चिम दैनिक',
                'position' => 'केन्द्रीय सदस्य',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000010',
                'approved_at' => now()->subMonths(6),
                'category_id' => $centralMembers->id,
            ],
            [
                'full_name' => 'कमला शर्मा',
                'email' => 'kamala.sharma@fnjnepal.org',
                'phone' => '9841234577',
                'citizenship_number' => '12-01-85-12355',
                'date_of_birth' => '1985-01-30',
                'gender' => 'female',
                'address' => 'जनकपुर, नेपाल',
                'education' => 'जनसञ्चारमा स्नातक',
                'experience_years' => 9,
                'current_workplace' => 'मधेश दैनिक',
                'position' => 'केन्द्रीय सदस्य',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000011',
                'approved_at' => now()->subMonths(6),
                'category_id' => $centralMembers->id,
            ],
            [
                'full_name' => 'राम बहादुर तामाङ',
                'email' => 'ram.tamang@fnjnepal.org',
                'phone' => '9841234578',
                'citizenship_number' => '12-01-86-12356',
                'date_of_birth' => '1986-10-08',
                'gender' => 'male',
                'address' => 'सिन्धुपाल्चोक, नेपाल',
                'education' => 'पत्रकारितामा स्नातक',
                'experience_years' => 8,
                'current_workplace' => 'पहाड दैनिक',
                'position' => 'केन्द्रीय सदस्य',
                'membership_type' => 'regular',
                'status' => 'approved',
                'member_id' => 'FNJ-2024-000012',
                'approved_at' => now()->subMonths(6),
                'category_id' => $centralMembers->id,
            ],
        ];

        foreach ($members as $memberData) {
            Membership::create($memberData);
        }
    }
}